# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('inspection_serial_num', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('inspection_business_name', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('inspection_score', models.IntegerField()),
                ('inspection_type', models.CharField(max_length=100)),
                ('inspection_result', models.CharField(max_length=100)),
                ('violation_description', models.CharField(blank=True, max_length=100)),
                ('violation_points', models.CharField(max_length=100)),
                ('violation_record_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_eats_app.InspectionReport')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('business_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('inspection_closed_business', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('longitude', models.FloatField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_eats_app.RestaurantInfo'),
        ),
    ]
