# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
