# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eats_app', '0002_auto_20170512_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
