# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eats_app', '0002_restaurantinfo_business_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantinfo',
            old_name='business_closed',
            new_name='inspection_closed_business',
        ),
    ]
