# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eats_app', '0003_auto_20160413_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='inspectionresult',
            name='violation_record_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
