# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_eats_app', '0005_auto_20160419_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
